------------------------------------------------------
-- Autor       : CESUR MALAGA         
-- Descripción : Create Table - Equipo
-- Responsable : Juan Alejandro Tellez Rubio
-- Alumno 1    : Manuel Recio Claros
-- Alumno 2    : Alvaro Gonzalez Rando
-- Alumno 3    : Alejandro Rebola Casquero
-- Alumno 4    : David Navarro Fajardo
------------------------------------------------------

INSERT INTO JUGADOR (ID_JUGADOR, NOMBRE, APELLIDO, ID_EQUIPO, DORSAL, P_JUGADOS, G_ANOTADOS) VALUES ('00000001A', 'Antonin', 'Cortes', 'Malaga F.C.', '1', '36', '9');
INSERT INTO JUGADOR (ID_JUGADOR, NOMBRE, APELLIDO, ID_EQUIPO, DORSAL, P_JUGADOS, G_ANOTADOS) VALUES ('00000002A', 'Aleixs', 'Febas', 'Malaga F.C.', '2', '36', '7');
INSERT INTO JUGADOR (ID_JUGADOR, NOMBRE, APELLIDO, ID_EQUIPO, DORSAL, P_JUGADOS, G_ANOTADOS) VALUES ('00000003A', 'Alvaro', 'Vadillo', 'Malaga F.C.', '3', '36', '3');
INSERT INTO JUGADOR (ID_JUGADOR, NOMBRE, APELLIDO, ID_EQUIPO, DORSAL, P_JUGADOS, G_ANOTADOS) VALUES ('00000004A', 'Ramon', 'Enriquez', 'Malaga F.C.', '4', '36', '4');
INSERT INTO JUGADOR (ID_JUGADOR, NOMBRE, APELLIDO, ID_EQUIPO, DORSAL, P_JUGADOS, G_ANOTADOS) VALUES ('00000005A', 'Genaro', 'Rodriguez', 'Malaga F.C.', '5', '36', '0');
INSERT INTO JUGADOR (ID_JUGADOR, NOMBRE, APELLIDO, ID_EQUIPO, DORSAL, P_JUGADOS, G_ANOTADOS) VALUES ('00000006A', 'Jozabed', 'Sanchez', 'Malaga F.C.', '6', '36', '0');
INSERT INTO JUGADOR (ID_JUGADOR, NOMBRE, APELLIDO, ID_EQUIPO, DORSAL, P_JUGADOS, G_ANOTADOS) VALUES ('00000007A', 'Alberto', 'Escassi', 'Malaga F.C.', '7', '36', '1');
INSERT INTO JUGADOR (ID_JUGADOR, NOMBRE, APELLIDO, ID_EQUIPO, DORSAL, P_JUGADOS, G_ANOTADOS) VALUES ('00000008A', 'Victor', 'Gomez', 'Malaga F.C.', '8', '36', '0');
INSERT INTO JUGADOR (ID_JUGADOR, NOMBRE, APELLIDO, ID_EQUIPO, DORSAL, P_JUGADOS, G_ANOTADOS) VALUES ('00000009A', 'Mathieu', 'Peybernes', 'Malaga F.C.', '9', '36', '0');
INSERT INTO JUGADOR (ID_JUGADOR, NOMBRE, APELLIDO, ID_EQUIPO, DORSAL, P_JUGADOS, G_ANOTADOS) VALUES ('00000010A', 'Javi', 'Jimenez', 'Malaga F.C.', '10', '36', '0');
INSERT INTO JUGADOR (ID_JUGADOR, NOMBRE, APELLIDO, ID_EQUIPO, DORSAL, P_JUGADOS, G_ANOTADOS) VALUES ('00000011A', 'Dani', 'Martin', 'Malaga F.C.', '11', '36', '0');
INSERT INTO JUGADOR (ID_JUGADOR, NOMBRE, APELLIDO, ID_EQUIPO, DORSAL, P_JUGADOS, G_ANOTADOS) VALUES ('00000001B', 'Darwin', 'Machis', 'Granada F.C.', '1', '31', '17');
INSERT INTO JUGADOR (ID_JUGADOR, NOMBRE, APELLIDO, ID_EQUIPO, DORSAL, P_JUGADOS, G_ANOTADOS) VALUES ('00000002B', 'Luis', 'Suarez', 'Granada F.C.', '2', '31', '11');
INSERT INTO JUGADOR (ID_JUGADOR, NOMBRE, APELLIDO, ID_EQUIPO, DORSAL, P_JUGADOS, G_ANOTADOS) VALUES ('00000003B', 'Yan Brice', 'Eteki', 'Granada F.C.', '3', '31', '3');
INSERT INTO JUGADOR (ID_JUGADOR, NOMBRE, APELLIDO, ID_EQUIPO, DORSAL, P_JUGADOS, G_ANOTADOS) VALUES ('00000004B', 'Njegos', 'Petrovic', 'Granada F.C.', '4', '31', '6');
INSERT INTO JUGADOR (ID_JUGADOR, NOMBRE, APELLIDO, ID_EQUIPO, DORSAL, P_JUGADOS, G_ANOTADOS) VALUES ('00000005B', 'Luis', 'Milla', 'Granada F.C.', '5', '31', '0');
INSERT INTO JUGADOR (ID_JUGADOR, NOMBRE, APELLIDO, ID_EQUIPO, DORSAL, P_JUGADOS, G_ANOTADOS) VALUES ('00000006B', 'Sergio', 'Escudero', 'Granada F.C.', '6', '31', '1');
INSERT INTO JUGADOR (ID_JUGADOR, NOMBRE, APELLIDO, ID_EQUIPO, DORSAL, P_JUGADOS, G_ANOTADOS) VALUES ('00000007B', 'Domingos', 'Duarte', 'Granada F.C.', '7', '31', '0');
INSERT INTO JUGADOR (ID_JUGADOR, NOMBRE, APELLIDO, ID_EQUIPO, DORSAL, P_JUGADOS, G_ANOTADOS) VALUES ('00000008B', 'Victor', 'Diaz', 'Granada F.C.', '8', '31', '0');
INSERT INTO JUGADOR (ID_JUGADOR, NOMBRE, APELLIDO, ID_EQUIPO, DORSAL, P_JUGADOS, G_ANOTADOS) VALUES ('00000009B', 'Myrto', 'Uzuni', 'Granada F.C.', '9', '31', '0');
INSERT INTO JUGADOR (ID_JUGADOR, NOMBRE, APELLIDO, ID_EQUIPO, DORSAL, P_JUGADOS, G_ANOTADOS) VALUES ('00000010B', 'Raul', 'Torrente', 'Granada F.C.', '10', '31', '0');
INSERT INTO JUGADOR (ID_JUGADOR, NOMBRE, APELLIDO, ID_EQUIPO, DORSAL, P_JUGADOS, G_ANOTADOS) VALUES ('00000011B', 'Luis', 'Maximiliano', 'Granada F.C.', '11', '31', '0');

COMMIT;